version: '3.9'
services:
  app:
    container_name: relation_service
    build:
      context: ./services/relation_service
      target: dev
    environment:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DB: neo4j
      AMQP_USER: user
      AMQP_PASSWORD: password
      AMQP_HOST: localhost
      AMQP_PORT: 5672
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - rabbitmq
    volumes:
      - ./services/relation_service/src:/relation_service/src

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "neo4j status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
      image: "rabbitmq:3-management"
      ports:
        - "5672:5672" # RabbitMQ server
        - "15672:15672" # Management console
      environment:
        RABBITMQ_DEFAULT_USER: "user"
        RABBITMQ_DEFAULT_PASS: "password"
      volumes:
        - "rabbitmq_data:/var/lib/rabbitmq"


volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
  rabbitmq_data:
