apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
  labels:
    name: auth-app-service
    micro-service: auth-service
    app: g-chat-app
spec:
  type: NodePort
  selector:
    name: auth-app-pod
    micro-service: auth-service
    app: g-chat-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
