apiVersion:  v1
kind: Service
metadata:
  name: chat-service-svc
  labels:
    name: chat-service-svc
    micro-service: chat-service
    app: g-chat-app
spec:
  type: ClusterIP
  selector:
    name: chat-app-pod
    micro-service: chat-service
    app: g-chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085