apiVersion:  v1
kind: Service
metadata:
  name: chat-service-svc
  labels:
    name: chat-service-svc
    micro-service: chat-service
    app: g-chat-app
spec:
  type: NodePort
  selector:
    name: chat-app-pod
    micro-service: chat-service
    app: g-chat-app
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30007
