apiVersion: v1
kind: Pod
metadata:
  name: neo4j-pod
  labels:
    name: neo4j-pod
    micro-service: neo4j-service
    app: g-chat-app
spec:
  containers:
    - name: neo4j
      image: neo4j:latest
      ports:
        - containerPort: 7474
        - containerPort: 7687
      env:
        - name: NEO4J_AUTH
          value: neo4j/password