apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  labels:
    name: postgres-service
    micro-service: postgres-service
    app: g-chat-app
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    micro-service: postgres-service
    app: g-chat-app
