--- # Auth postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth-deploy
  labels:
    app: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: auth
            - name: POSTGRES_PASSWORD
              value: auth
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_HOST
              value: postgres-auth-service
          volumeMounts:
            - name: postgres-auth-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-auth-data
          persistentVolumeClaim:
            claimName: postgres-auth-data-claim
--- # Chat postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-chat-deploy
  labels:
    app: chat-db-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-db-master
  template:
    metadata:
      labels:
        app: chat-db-master
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: chat_service
            - name: POSTGRES_PASSWORD
              value: chat_service
            - name: POSTGRES_DB
              value: chat_service
            - name: POSTGRES_HOST
              value: chat-db-master
          volumeMounts:
            - name: postgres-chat-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-chat-data
          persistentVolumeClaim:
            claimName: postgres-chat-data-claim