apiVersion: v1
kind: Service
metadata:
  name: relation-app-service
  labels:
    name: relation-app-service
    micro-service: relation-service
    app: g-chat-app
spec:
  type: ClusterIP
  selector:
    name: relation-app-pod
    micro-service: relation-service
    app: g-chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000