apiVersion: k3d.io/v1alpha3
kind: Simple
name: mycluster
servers: 1
image: docker.io/rancher/k3s:v1.27.4-k3s1
ports:
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 8090:8090
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
