apiVersion: v1
kind: Pod

metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    micro-service: postgres-service
    app: g-chat-app
spec:
  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
          name: default
      env:
        - name: POSTGRES_USER
          value: auth
        - name: POSTGRES_PASSWORD
          value: auth
        - name: POSTGRES_DB
          value: auth
        - name: POSTGRES_HOST
          value: auth-db
      volumeMounts: # Volumes to mount
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data-claim