--- # Auth postgres pod
apiVersion: v1
kind: Pod
metadata:
  name: postgres-auth-pod
  labels:
    app: auth-db
spec:
  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: auth
        - name: POSTGRES_PASSWORD
          value: auth
        - name: POSTGRES_DB
          value: auth
        - name: POSTGRES_HOST
          value: auth-db
      volumeMounts:
        - name: postgres-auth-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-auth-data
      persistentVolumeClaim:
        claimName: postgres-auth-data-claim
--- # Chat postgres pod
apiVersion: v1
kind: Pod
metadata:
  name: postgres-chat-pod
  labels:
    app: chat-db
spec:
  containers:
    - name: postgres
      image: postgres:16
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: chat_service
        - name: POSTGRES_PASSWORD
          value: chat_service
        - name: POSTGRES_DB
          value: chat_service
        - name: POSTGRES_HOST
          value: postgresql-master
      volumeMounts:
        - name: postgres-chat-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-chat-data
      persistentVolumeClaim:
        claimName: postgres-chat-data-claim
