apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis-pod
    micro-service: redis-service
    app: g-chat-app
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: redis-data-pvc