site_name: My FastAPI Docs
theme:
  name: 'material'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
nav:
  - Home: index.md
  - API:
      - Overview: api.md
      - Endpoints:
          - Chat: api/chat.md
          - ChatMessage: api/chat_message.md
          - Demo: api/demo.md
          - Echo: api/echo.md
          - Monitoring: api/monitoring.md
          - Server: api/server.md
          - ServerMember: api/server_member.md
          - ServerMessage: api/server_message.md
          - Websocket: api/ws.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true
