version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - auth-db
      - rabbitmq
    environment:
      AUTHSERVICE_HOST: 0.0.0.0
      # Database
      AUTHSERVICE_DB_HOST: auth-db
      AUTHSERVICE_DB_PORT: 5432
      AUTHSERVICE_DB_USER: auth
      AUTHSERVICE_DB_PASSWORD: auth
      AUTHSERVICE_DB_NAME: auth
      # RabbitMQ
      AUTHSERVICE_RABBITMQ_HOST: rabbitmq
      AUTHSERVICE_RABBITMQ_PORT: 5672
      AUTHSERVICE_RABBITMQ_USER: user
      AUTHSERVICE_RABBITMQ_PASSWORD: password
    volumes:
      - ./src:/app
      - ./:/app

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
      POSTGRES_HOST: auth-db
    ports:
      - 5433:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U auth
      interval: 2s
      timeout: 3s
      retries: 40

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management console
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    
volumes:
  auth-db-data:
  rabbitmq_data:

