version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - auth-db
    environment:
      AUTHSERVICE_HOST: 0.0.0.0
      AUTHSERVICE_DB_HOST: auth-db
      AUTHSERVICE_DB_PORT: 5432
      AUTHSERVICE_DB_USER: auth
      AUTHSERVICE_DB_PASSWORD: auth
      AUTHSERVICE_DB_NAME: auth
    
    networks:
      - auth-service-network
      
  auth-db:
    image: postgres:13
    container_name: auth-db
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
      POSTGRES_DB: auth
      POSTGRES_HOST: auth-db
    ports:
      - 5433:5432
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U auth
      interval: 2s
      timeout: 3s
      retries: 40
    
    networks:
      - auth-service-network
    
volumes:
  auth-db-data:


networks:
  auth-service-network:
    driver: bridge