name: Deploy to Azure Kubernetes Service

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to deploy"
        required: true
        default: "auth_service"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Azure login
        uses: azure/login@v2
        with:
            auth-type: IDENTITY
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            enable-AzPSSession: true
  
      - name: Install kubectl
        uses: azure/setup-kubectl@v1

      - name: Set context to AKS
        run: az aks get-credentials --name ${{ secrets.AKS_CLUSTER_NAME }} --resource-group ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Update Kubernetes deployment
        run: |
          kubectl config get-contexts
